(require 'smartparens-config)
(add-hook 'emacs-lisp-mode-hook 'smartparens-mode)
(add-hook 'lisp-interaction-mode-hook 'smartparens-mode)
(add-hook 'lisp-mode-hook 'smartparens-mode)
(add-hook 'ielm-mode-hook 'smartparens-mode)
(add-hook 'slime-repl-mode-hook 'smartparens-mode)
(add-hook 'inferior-lisp-mode-hook 'smartparens-mode)
(add-hook 'scheme-mode-hook 'smartparens-mode)
(add-hook 'inferior-scheme-mode-hook 'smartparens-mode)
(add-hook 'clojure-mode-hook 'smartparens-mode)
(add-hook 'nrepl-mode-hook 'smartparens-mode)
(add-hook 'cider-repl-mode-hook 'smartparens-mode)
(add-hook 'js2-mode-hook 'smartparens-mode)
(add-hook 'java-mode-hook 'smartparens-mode)
(add-hook 'eshell-mode-hook 'smartparens-mode)
(add-hook 'html-mode-hook 'smartparens-mode)
(add-hook 'web-mode-hook 'smartparens-mode)
